### ISSUE TITLE
Release with a more permissive license?

### ISSUE THREAD

**Issue by sztomi** [benjibc/constexpr_hash_map#1]
Hi!

I would like to integrate this library into a MIT licensed open-source project, but the GPL prevents me from doing that. I would prefer not to adopt the GPL. Have you thought about using a different license (MIT or BSD or similar)? Or possibly dual-licensing.

**Comment by benjibc** [comment]
LOL I just saw this. So sorry this was one of the old ones and I didn't understand the difference between GPL and MIT, let me change the license

**Comment by sztomi** [comment]
No problem. I was just thinking about picking up that project again, so the timing is perfect :)

**Comment by benjibc** [comment]
Done. Re-open if you need anything else from me for licensing
